name: Install and Configure gcloud CLI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  install-gcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Package webappOrg-main directory
        run: zip -r checkwebapp-main.zip checkwebapp-main

      - name: Copy artifact to Packer build context
        run: cp checkwebapp-main.zip /checkwebapp     
