name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_status_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.7/packer_1.8.7_linux_amd64.zip
          unzip packer_1.8.7_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Check Packer formatting
        run: |
          packer fmt -check .

      - name: Validate Packer template
        run: |
          packer validate .
