name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_status_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.8.7

      - name: Initializing the plugins
        run: |
          packer init .

      - name: Check Packer formatting
        run: |
          packer fmt -check .

      - name: Validate Packer template
        run: |
          packer validate .
